server:
  port: 6003

spring:
  application:
    name: mic-auth

  datasource:
    url: jdbc:postgresql://localhost:5432/micAuth
    username: userAuth
    password: passAuth
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    #clear-checksums: true

  springdoc:
    show-actuator: true
    packagesToScan:
      - com.nexaplatform.api
