server:
  port: 9001

spring:
  application:
    name: mic-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/productcategory
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9001
  springdoc:
    oauth2:
      client-id: swagger-client
      client-secret: swagger-secret

temporal:
  secret: client
  issuer-url: http://localhost:9001
  post-logout-url: http://localhost:9001
  redirect-url: https://oauthdebugger.com/debug

#logging:
#  level:
#    root: DEBUG
#    org:
#      springframework:
#        security: DEBUG
#        security.web.authentication: DEBUG
#        security.authentication: DEBUG
#        security.access: DEBUG
#        security.oauth2: DEBUG