server:
  port: 9001

api:
  title: Mic Auth-microservices
  version: v1.0.0
  description: This is the documentation related to the administration of the user microservice

spring:
  profiles:
    active: ${ENV:local}

  springdoc:
    show-actuator: true