apiVersion: apps/v1
kind: Deployment
metadata:
  name: mic-auth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mic-auth
  template:
    metadata:
      labels:
        app: mic-auth
    spec:
      containers:
        - name: mic-auth-container # Nombre del contenedor (puede ser mic-auth)
          # <<<--- ¡IMPORTANTE! Reemplaza con la imagen de tu microservicio construida por tu CI
          # Ejemplo: tu-registro-docker/mic-auth:0.0.1-SNAPSHOT
          # O mejor aún, usa una etiqueta basada en el commit o build number:
          image: tu-registro-docker/mic-auth:latest # <<<--- ¡REEMPLAZA ESTO!
          ports:
            - containerPort: 8080 # El puerto en el que escucha tu aplicación Java (puerto interno del contenedor)
          env: # Ejemplo de variables de entorno (adapta a tu application.yml)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://mi-base-de-datos:5432/mydb"
          # Añade aquí otras configuraciones necesarias (limits, probes, etc.)