apiVersion: v1
kind: Service
metadata:
  name: mic-auth-service # Nombre de tu Service
  namespace: default # Debe ser el mismo namespace que el Deployment
spec:
  selector:
    app: mic-auth # Debe coincidir con las labels del pod en el Deployment
  ports:
    - protocol: TCP
      port: 80 # Puerto del Service (cómo se accede desde dentro del clúster)
      targetPort: 8080 # Puerto del contenedor (el containerPort del Deployment)
  type: ClusterIP # O NodePort, LoadBalancer, etc., dependiendo de cómo quieras acceder