version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: db-mic-auth
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: micAuth
      POSTGRES_USER: userAuth
      POSTGRES_PASSWORD: passAuth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U userAuth -d micAuth" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - default_network

volumes:
  postgres_data:

networks:
  default_network:
    driver: bridge